name: Create release

on:
  create:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ZIPNAME: Sons-Of-The-Forest-Inventory-Editor_${{ github.ref_name }}.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the ZIP archive
        run: php build.php

      - name: Rename the ZIP archive
        run: |
          cd dist
          mv Sons-Of-The-Forest-Inventory-Editor.zip ../${{ env.ZIPNAME }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ZIPNAME }}
          draft: true

      - uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ${{ env.ZIPNAME }}
          path: ${{ env.ZIPNAME }}
